version: 2.1
orbs:
  yarn: itinerisltd/yarn@2.1.1
parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  model:
    type: boolean
    default: false
  engine:
    type: boolean
    default: false
  designer:
    type: boolean
    default: false
  runner:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node:12
  node-browsers:
    docker:
      - image: circleci/node:12.16-browsers
  python:
    docker:
      - image: circleci/python:2.7-jessie

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    parameters:
      package_name:
        type: string

    executor: node-browsers
    working_directory: ~/project

    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            # fallback to using the latest cache if no exact match is found
            - root-dependencies-{{ checksum "yarn.lock" }}
            - root-dependencies
            - << parameters.package_name >>/flow-typed


      - yarn/install-packages-if-changed:
          paths: << parameters.package_name >>

      - save_cache:
          paths:
            - node_modules
          key: root-dependencies-{{ checksum "yarn.lock" }}

      - save_cache:
          paths:
            - << parameters.package_name >>/flow-typed
          key: << parameters.package_name >>-flow-typed-{{ checksum "yarn.lock" }}

      - run:
          name: Build
          command: |
            yarn workspace @xgovformbuilder/<< parameters.package_name >> run build

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  test:
    parameters:
      package_name:
        type: string

    executor: node-browsers

    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Test
          command: yarn workspace @xgovformbuilder/<< parameters.package_name >> run test

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows


  # Workflows defined for each package.

  model:
    when: << pipeline.parameters.model >>
    jobs:
      - build:
          name: model-build
          package_name: model
      - test:
          name: model-test
          package_name: model
          requires:
            - model-build

  engine:
    when: << pipeline.parameters.engine >>
    jobs:
      - build:
          name: model-build
          package_name: model
      - build:
          name: engine-build
          package_name: engine
          requires:
            - model-build
      - test:
          name: engine-test
          package_name: engine
          requires:
            - engine-build

  designer:
    when: << pipeline.parameters.designer >>
    jobs:
      - build:
          name: designer-build
          package_name: designer
      - test:
          name: designer-test
          package_name: designer
          requires:
            - designer-build

  runner:
    when: << pipeline.parameters.runner >>
    jobs:
      - build:
          name: runner-build
          package_name: runner
      - test:
          name: runner-test
          package_name: runner
          requires:
            - runner-build
