version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  model:
    type: boolean
    default: false
  engine:
    type: boolean
    default: false
  designer:
    type: boolean
    default: false
  runner:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node:12
  node-browsers:
    docker:
      - image: circleci/node:12-browsers

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    parameters:
      package_name:
        type: string

    executor: node-browsers
    working_directory: ~/project/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          keys:
            - << parameters.package_name >>-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - << parameters.package_name >>-dependencies-

      - run: yarn install

      - run:
          name: Re-link model
          command: |
            rm -fr node_modules/digital-form-builder-model
            yarn --check-files

      - run:
          name: Re-link engine
          command: |
            rm -fr node_modules/digital-form-builder-engine
            yarn --check-files

      - save_cache:
          paths:
            - node_modules
            - flow-typed
          key: << parameters.package_name >>-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: |
            yarn build

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  test:
    parameters:
      package_name:
        type: string

    executor: node-browsers
    working_directory: ~/project/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project

      - run:
          name: Re-link model
          command: |
            rm -fr node_modules/digital-form-builder-model
            yarn --check-files

      - run:
          name: Re-link engine
          command: |
            rm -fr node_modules/digital-form-builder-engine
            yarn --check-files

      - run:
          name: Test
          command: yarn test-cov

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-coverage

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows


  # Workflows defined for each package.

  model:
    when: << pipeline.parameters.model >>
    jobs:
      - build:
          name: model-build
          package_name: model
      - test:
          name: model-test
          package_name: model
          requires:
            - model-build

  engine:
    when: << pipeline.parameters.engine >>
    jobs:
      - build:
          name: model-build
          package_name: model
      - build:
          name: engine-build
          package_name: engine
          requires:
            - model-build
      - test:
          name: engine-test
          package_name: engine
          requires:
            - engine-build

  designer:
    when: << pipeline.parameters.designer >>
    jobs:
      - build:
          name: model-build
          package_name: model
      - build:
          name: designer-build
          package_name: designer
          requires:
            - model-build
      - test:
          name: designer-test
          package_name: designer
          requires:
            - designer-build

  runner:
    when: << pipeline.parameters.runner >>
    jobs:
      - build:
          name: model-build
          package_name: model
      - build:
          name: engine-build
          package_name: engine
          requires:
            - model-build
      - build:
          name: runner-build
          package_name: runner
          requires:
            - engine-build
      - test:
          name: runner-test
          package_name: runner
          requires:
            - runner-build
